spring:
  datasource:
    url: jdbc:postgresql://north-wombat-11209.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=${user.home}/AppData/Roaming/postgresql/root.crt
    username: siddharth
    password: bBs7aID7sj7xYrvgJmxU7Q
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariCockroachPool
